"""Refactor

Revision ID: 04dcec44f92e
Revises: ca5545b72cd5
Create Date: 2025-11-02 21:41:01.484629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04dcec44f92e'
down_revision = 'ca5545b72cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_title', sa.String(length=100), nullable=False),
    sa.Column('report_body', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
