"""Auto-migrate (Render)

Revision ID: ae78e9439e9f
Revises: 
Create Date: 2025-10-26 18:20:31.797696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae78e9439e9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('admin_user_name', sa.String(length=100), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('closing_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_closing_sessions_session_date'), ['session_date'], unique=False)

    op.create_table('csanames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendant_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendant_name')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('shop_code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('shop_code')
    )
    op.create_table('coins_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('coin_5', sa.Integer(), nullable=True),
    sa.Column('coin_2', sa.Integer(), nullable=True),
    sa.Column('coin_1', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_reconciliation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['closing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='unique_coins_per_session')
    )
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('gcb', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('momo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tingg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('zenith', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('republic', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prudential', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('adb', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stanbic', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ecobank', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fidelity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_ab', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_cf', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_gc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_wl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_zl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('soc_staff_credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('water_bill', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ecg_bill', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('genset', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('approve_miscellaneous', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('collection_ab', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('collection_wl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('collection_zl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('collection_gc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('collection_cv', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lube_1_liter', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lube_drum', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('duster_collection', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_collection', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cash_to_bank', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['closing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='unique_credit_per_session')
    )
    op.create_table('d14_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('d1_opening', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('d1_closing', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('d2_opening', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('d2_closing', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('d3_opening', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('d3_closing', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('d4_opening', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('d4_closing', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rtt_liters', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('liters_sold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date_of_sale', sa.Date(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('csa_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['closing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('d14_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_d14_readings_section'), ['section'], unique=False)

    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('super_1_opening', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('super_2_opening', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('super_1_closing', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('super_2_closing', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('liters_sold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gsa_test_draw', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date_of_sale', sa.Date(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('csa_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['closing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meter_readings_section'), ['section'], unique=False)

    op.create_table('paper_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('note_200', sa.Integer(), nullable=True),
    sa.Column('note_100', sa.Integer(), nullable=True),
    sa.Column('note_50', sa.Integer(), nullable=True),
    sa.Column('note_20', sa.Integer(), nullable=True),
    sa.Column('note_10', sa.Integer(), nullable=True),
    sa.Column('note_5', sa.Integer(), nullable=True),
    sa.Column('note_2', sa.Integer(), nullable=True),
    sa.Column('note_1', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_reconciliation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['closing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='unique_paper_per_session')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('staff_id', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.String(length=100), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('is_default_credential', sa.Boolean(), nullable=True),
    sa.Column('user_profile', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('user_idx', ['date_created'], unique=False)

    op.drop_table('daily_acct_mgr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_acct_mgr',

    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('user_idx')

    op.drop_table('users')
    op.drop_table('paper_transactions')
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meter_readings_section'))

    op.drop_table('meter_readings')
    with op.batch_alter_table('d14_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_d14_readings_section'))

    op.drop_table('d14_readings')
    op.drop_table('credit_transactions')
    op.drop_table('coins_transactions')
    op.drop_table('tenants')
    op.drop_table('csanames')
    with op.batch_alter_table('closing_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_closing_sessions_session_date'))

    op.drop_table('closing_sessions')
    # ### end Alembic commands ###
